# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x06worker\"D\n\x11SubmitTaskRequest\x12\x1e\n\x04type\x18\x01 \x01(\x0e\x32\x10.worker.TaskType\x12\x0f\n\x07payload\x18\x02 \x01(\t\"%\n\x12SubmitTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\'\n\x14GetTaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"U\n\nTaskStatus\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.worker.TaskStatusEnum\x12\x0e\n\x06result\x18\x03 \x01(\t*B\n\x08TaskType\x12\x19\n\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x0c\n\x08LLM_CALL\x10\x01\x12\r\n\tPR_REVIEW\x10\x02*a\n\x0eTaskStatusEnum\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\n\n\x06QUEUED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\r\n\tSUCCEEDED\x10\x03\x12\n\n\x06\x46\x41ILED\x10\x04\x32\x90\x01\n\x06Worker\x12\x43\n\nSubmitTask\x12\x19.worker.SubmitTaskRequest\x1a\x1a.worker.SubmitTaskResponse\x12\x41\n\rGetTaskStatus\x12\x1c.worker.GetTaskStatusRequest\x1a\x12.worker.TaskStatusB.Z,github.com/onepersonai/worker/proto;workerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/onepersonai/worker/proto;workerpb'
  _globals['_TASKTYPE']._serialized_start=261
  _globals['_TASKTYPE']._serialized_end=327
  _globals['_TASKSTATUSENUM']._serialized_start=329
  _globals['_TASKSTATUSENUM']._serialized_end=426
  _globals['_SUBMITTASKREQUEST']._serialized_start=24
  _globals['_SUBMITTASKREQUEST']._serialized_end=92
  _globals['_SUBMITTASKRESPONSE']._serialized_start=94
  _globals['_SUBMITTASKRESPONSE']._serialized_end=131
  _globals['_GETTASKSTATUSREQUEST']._serialized_start=133
  _globals['_GETTASKSTATUSREQUEST']._serialized_end=172
  _globals['_TASKSTATUS']._serialized_start=174
  _globals['_TASKSTATUS']._serialized_end=259
  _globals['_WORKER']._serialized_start=429
  _globals['_WORKER']._serialized_end=573
# @@protoc_insertion_point(module_scope)
